### ISSUE TITLE
no error handling

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-reports-floodgauge#2]

**Comment by tomasholderness** [comment]
https://github.com/urbanriskmap/cognicity-reports-floodgauge/blob/master/FloodgaugeDataSource.js#L139 catches errors when connecting to the data provider, can you check the logs and see if there was an error message printed?

**Comment by matthewberryman** [comment]
Sorry, you're right (my bad for getting confused at 2am), the errors was elsewhere in reports.

**Comment by tomasholderness** [comment]
No problem :)
